# Generated by Django 3.0.3 on 2020-04-12 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FPSRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopid', models.CharField(max_length=20)),
                ('shop_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Reports',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopid', models.CharField(max_length=20)),
                ('date', models.DateField(auto_now=True)),
                ('report', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(max_length=20)),
                ('shopid', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wheat', models.IntegerField()),
                ('rice', models.IntegerField()),
                ('dal', models.IntegerField()),
                ('kerosene', models.IntegerField()),
                ('shopid', models.CharField(default='SOME STRING', max_length=20)),
                ('shop', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='FPS.Shop')),
            ],
        ),
    ]
