# Generated by Django 3.0.3 on 2020-04-18 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FPS', '0003_fpsrequest_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fpsrequest',
            name='shop_name',
        ),
        migrations.RemoveField(
            model_name='fpsrequest',
            name='shopid',
        ),
        migrations.RemoveField(
            model_name='reports',
            name='shopid',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='shopid',
        ),
    ]
