# Generated by Django 3.0.3 on 2020-04-18 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FPS', '0004_auto_20200418_1414'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shop',
            old_name='shop',
            new_name='user',
        ),
    ]
