# Generated by Django 3.0.3 on 2020-04-26 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FPS', '0006_soldration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reports',
            name='report',
        ),
    ]
