# Generated by Django 3.0.3 on 2020-04-26 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FPS', '0007_remove_reports_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='fpsrequest',
            name='date_month',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='fpsrequest',
            name='date_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reports',
            name='date_month',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='reports',
            name='date_year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
