# Generated by Django 3.0.3 on 2020-04-26 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FPS', '0009_auto_20200426_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='soldration',
            name='date_month',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='soldration',
            name='date_year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
