# Generated by Django 3.0.3 on 2020-04-26 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FPS', '0010_auto_20200426_2342'),
    ]

    operations = [
        migrations.AddField(
            model_name='soldration',
            name='shopid',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
