# Generated by Django 3.0.3 on 2020-04-12 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=20)),
                ('lname', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=200)),
                ('rationid', models.CharField(max_length=15)),
                ('shopid', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='RationSent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopid', models.CharField(max_length=15)),
                ('wheat', models.IntegerField()),
                ('rice', models.IntegerField()),
                ('dal', models.IntegerField()),
                ('kerosene', models.IntegerField()),
                ('data', models.DateField(auto_now=True)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ShopRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=200)),
                ('shopid', models.CharField(max_length=15)),
            ],
        ),
    ]
