# Generated by Django 3.0.3 on 2020-04-12 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Govt', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rationsent',
            old_name='data',
            new_name='date',
        ),
    ]
