# Generated by Django 3.0.3 on 2020-04-18 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_student',
            new_name='is_FPS',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='is_teacher',
            new_name='is_customer',
        ),
        migrations.AddField(
            model_name='user',
            name='is_govt',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
